services:
  service-log-main:
    restart: always
    image: log-main-service:v1
    container_name: log-main-service
    ports:
      - "8082:8080"
    env_file:
      - ../.env
    networks:
      - default
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6000:6379"
    networks:
      - default
    environment:
      - TZ=Asia/Kolkata
networks:
  default:
    driver: bridge
